### ISSUE TITLE
cache docker build steps better?

### ISSUE THREAD

**Issue by bnchdrff** [steemit/jussi#105]
how can the docker build time be shortened?

can we use a prebuilt python image so we're not downloading & rebuilding every time?

should the `ENV` settings get moved down in the dockerfile so the steps after them are cached? (not sure how that works, actually)

**Comment by john-g-g** [comment]
The long part is the python 3.6 compilation (3.6 is supported on this image's ubuntu yet), which should be cached unless something above that is changed. Moving the ENV directives below the python compilation would allow you to change then in the Dockerfile without recompiling python, but I'm curious about what and why you're having to change them. In a local dev setup, all env vars, dirs, and files can be overridden from the docker cli. There is also a [docker-compose file](https://github.com/steemit/jussi/blob/master/tests/docker-compose.yml) if you feel that is easier

**Comment by bnchdrff** [comment]
for local dev i changed `JUSSI_TEST_UPSTREAM_URLS`
