### ISSUE TITLE
Unable to call conveyor on dev

### ISSUE THREAD

**Issue by jnordberg** [steemit/jussi#106]
Not sure if jussi or config problem. Would be nice if jussi sat on the default config and the orchestration configs where just extending that where needed instead of maintaining 3 separate copies.

```js
{ code: 1200,
  message: 'Invalid JSONRPC method namespace conveyor.is_phone_registered',
  data: { error_id: '1bee1430-ca5b-4196-be9c-df375f620058' } }
```

**Comment by jnordberg** [comment]
cc @jredbeard

**Comment by jredbeard** [comment]
I believe the branch currently deployed to dev (appbase-compat) is an old branch that doesn't utilize the 'new' file config, so, it's probably being ignored and is why this is happening. When appbase-compat gets merged into master it will use that config again.

**Comment by john-g-g** [comment]
I'll leave this open until we merge the appbase compat branch, but @jredbeard's analysis is correct
