### ISSUE TITLE
Move back to using uvloop and/or multiprocessing when feasible

### ISSUE THREAD

**Issue by john-g-g** [steemit/jussi#12]
pragmatism dictated using the default event loop and no worker processes, implemented in https://github.com/steemit/jussi/pull/11 . For performance reasons, we should look into re-adopting them at our first convenience.

**Comment by GarethNelson** [comment]
Might it make sense to handle this out of process by switching to FastCGI?

**Comment by john-g-g** [comment]
Will you elaborate on the uvloop error you encountered that caused you to change approaches? I'm not convinced that it wasn't an error with our code and/or config. I think using FastCGI and multiple jussi processes might just be covering up an error in our code. Nginx-->Sanic is the canonical Sanic use case, and even it should work without error. Using FastCGI, In addition to increasing  system complexity, would add an extra layer that I suspect would negatively impact performance when compared to multiple Sanic worker processes and/or multiple Nginx upstream Sanic processes.  That said, I have no dogmatic loyalty to any framework or approach, so if you have empirical data that shows superior performance of another approach, then we will use it.
