### ISSUE TITLE
errors in dev 2018-02-08

### ISSUE THREAD

**Issue by roadscape** [steemit/jussi#120]
Over the course of ~12 hours I saw 2 distinct types of errors:

few dozen times, on `get_block`, `get_accounts`, `get_feed_history`:
`04:49:03.586 steemit-dev-jussi-001_i-0a7c6d61a91a4cc8d /var/log/messages Feb 8 10:49:01 ip-172-31-10-193 docker/d57e0bf4a57c[3503]: {"funcName": "log", "lineno": 164, "msecs": 113.94095420837402, "message": "{\'jsonrpc': '2.0', 'error': {'code': -32603, 'message': 'Internal Error', 'data': {'error_id': 'f525fb43-5f28-4899-a8d1-d0c856831709', 'request': {'amzn_trace_id': 'Root=1-5a7c2b1d-65fced5701fcdaf921a1ce9d', 'jussi_request_id': None}, 'exception': AssertionError(<websockets.client.WebSocketClientProtocol object at 0x7ff6c05e95c0>,)}}}", "name": "jussi.errors", "timestamp": "2018-02-08T10:49:01.1518086941UTC", "severity": "ERROR", "exc_info": "Traceback (most recent call last):\n File \"/app/.venv/lib/python3.6/site-packages/sanic/app.py\", line 503, in handle_request\n response = await response\n File \"/app/jussi/handlers.py\", line 37, in handle_jsonrpc\n jsonrpc_requests)\n File \"/app/jussi/handlers.py\", line 113, in dispatch_single\n jsonrpc_request)\n File \"/app/jussi/handlers.py\", line 58, in fetch_ws\n conn = await pool.acquire()\n File \"/app/jussi/ws/utils.py\", line 72, in __await__\n resp = yield from self._coro\n File \"/app/jussi/ws/pool.py\", line 259, in _acquire\n assert conn.open, conn\nAssertionError: <websockets.client.WebSocketClientProtocol object at 0x7ff6c05e95c0>"}`

1 time, on `get_block`:
`05:08:40.002 steemit-dev-jussi-001_i-0a7c6d61a91a4cc8d /var/log/messages Feb 8 11:08:37 ip-172-31-10-193 docker/d57e0bf4a57c[3503]: {"funcName": "log", "lineno": 164, "msecs": 85.82496643066406, "message": "{\'jsonrpc': '2.0', 'error': {'code': -32603, 'message': 'Internal Error', 'data': {'error_id': '3caf9e02-01e3-4afb-b7ad-b870eeffd3c8', 'request': {'amzn_trace_id': 'Root=1-5a7c2fb5-285783250a25ea3d54e982d6', 'jussi_request_id': None}, 'exception': KeyError(<websockets.client.WebSocketClientProtocol object at 0x7ff6c14feb00>,)}}}", "name": "jussi.errors", "timestamp": "2018-02-08T11:08:37.1518088117UTC", "severity": "ERROR", "exc_info": "Traceback (most recent call last):\n File \"/app/jussi/handlers.py\", line 62, in fetch_ws\n upstream_response_json = await conn.recv()\n File \"/app/.venv/lib/python3.6/site-packages/websockets/protocol.py\", line 323, in recv\n raise ConnectionClosed(self.close_code, self.close_reason)\nwebsockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File \"/app/jussi/ws/pool.py\", line 210, in terminate_connection\n conn.worker_task.cancel()\nAttributeError: 'WebSocketClientProtocol' object has no attribute 'worker_task'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File \"/app/.venv/lib/python3.6/site-packages/sanic/app.py\", line 503, in handle_request\n response = await response\n File \"/app/jussi/handlers.py\", line 37, in handle_jsonrpc\n jsonrpc_requests)\n File \"/app/jussi/handlers.py\", line 113, in dispatch_single\n jsonrpc_request)\n File \"/app/jussi/handlers.py\", line 85, in fetch_ws\n await pool.terminate_connection(conn)\n File \"/app/jussi/ws/pool.py\", line 216, in terminate_connection\n self._terminated.remove(conn)\nKeyError: <websockets.client.WebSocketClientProtocol object at 0x7ff6c14feb00>"}`

client config
`url:https://api.steemitdev.com batch:500 workers:1 appbase:True`

**Comment by john-g-g** [comment]
@roadscape is this still happening?
