### ISSUE TITLE
account_history_api_plugin not enabled

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/jussi#193]
# Problem

I am getting the message `Exception:_account_history_api: account_history_api_plugin not enabled.) in get_account_history` when trying to create a Jussi node with the latest version.

Ultimately I am trying to point Jussi at my nodes, but not having any luck.  I falled back on just using the default configuration and that is giving me the same problem pointing at the default node.

# Setup

Jussi/master as docker
Pointing to private full node (non-appbase)
Access Jussi via SteemJS & Steem-Python

# Things I tried 
["steemd.account_history_api.get_account_history","wss://rpc.buildteam.io"] in the URL section.

--env JUSSI_ACCOUNT_TRANSFER_STEEMD_URL=wss://rpc.buildteam.io during the startup of the container with no luck.

# Previous attempts
I installed a Jussi server about 4-5 days ago that worked fine, but now no matter how many times I install/build change configuration or leave it, I cannot get account_history to work.  I tried pointing to appbase and not appbase nodes (ultimately right now I need to point to non-appbase nodes).

Currently, I cannot install Jussi that doesn't have account history problems.  Even fresh install without any configuration changes.

# Install process

* git clone https://github.com/steemit/jussi
* cd jussi
* docker build -t="jussi" .
* docker run -it -p 9000:8080 jussi

**Comment by john-g-g** [comment]
Hi sorry to hear you're having trouble with jussi. That error message is from steemd, so my first question is are you sure you have the enabled the account_history_api_plugin on the node jussi is pointing to? If you are sure about that, then I'm happy to go over you upstream config file and env vars to help you troubleshoot.

**Comment by themarkymark-steem** [comment]
I've been working on this a lot, and I found the problem.  It appears to be related to Steem-python, it only happens with Steem-python, curl and steemjs work fine.  I'm going to close this as I don't believe this is actually Jussi related anymore and open it there.
