### ISSUE TITLE
Need increased timeout and cache time on `get_ops_in_block(2889020, false)`

### ISSUE THREAD

**Issue by mvandeberg** [steemit/jussi#213]
`get_ops_in_block(2889020, false)` queries a block with a large number of virtual ops and causes a timeout. The timeout should be increased on this call as well as the cache time to prevent going to steemd too often.

A 10 second timeout should be more than adequate. A 24 cache should also be good.

See steemit/steem#3141

**Comment by john-g-g** [comment]
In my testing, 10 seconds doesn't work, but 20 seconds does. I've updated the DEV config in the jussi repo, but changes to our dev/staging/prod environments will need to be updated in the configs for those environments
