### ISSUE TITLE
If the X-Amzn-Trace-Id header exists on incoming request, supply it to the backend service as X-Steemit-Trace-Id.

### ISSUE THREAD

**Issue by sneak** [steemit/jussi#5]
https://github.com/steemit/steempunks/issues/66

Also, include it in the logging.

**Comment by john-g-g** [comment]
Why rename the header instead of including it on the forwarded request?

**Comment by sneak** [comment]
Because I assume the second ELB will replace it with the unique trace-id from the second request.

**Comment by john-g-g** [comment]
x-amzn-trace-id headers are appended with unique ids as they traverse aws services
