### ISSUE TITLE
Stability Issues (timeout, lock errors)

### ISSUE THREAD

**Issue by roadscape** [steemit/jussi#85]
Seems to be a new issue; my error rate w/ jussi had been 0 for weeks until 1-2 weeks ago (early January).

These errors are reliably caused by batch `get_content` calls. There were issues with `get_blocks` last week but it's more stable now. Here's a sampling of errors received in a 6-minute period:

`81d0fcf0-b082-4f62-9b3d-1cd3eb511c9e` - `RuntimeError('Lock is not acquired.',)`
`98799471-e0eb-4628-a416-bf35607b4dd6` - `TimeoutError()`
`65699ebd-f701-4fff-b052-8a6e678e4572` - `TimeoutError()`
`f7625fca-e51c-4913-bcad-1c7ecfddcced` - `TimeoutError()`
`68e6eaaa-4cf6-4c2c-90df-bdfb9690e0bb` - `TimeoutError()`
`20a24b89-50fa-4bc2-b136-7a1ed7d053c8` - `TimeoutError()`
`d0aee746-8ae2-4326-8f48-fd43d6f21bc3` - `TimeoutError()`
`72192a1c-d4e2-42b7-93fb-5a63b3bd4853` - `TimeoutError()`
`7ef8f6cc-7269-47c7-9402-e66a9f17a92c` - `TimeoutError()`
`2ae32166-1a33-4037-bd7c-b558f266701a` - `TimeoutError()`
`7a23ceb1-9898-413a-a8ed-614052b0bcfe` - `RuntimeError('Lock is not acquired.',)`
`d20c156f-145a-42e6-a344-5398c91b66a7` - `TimeoutError()`
`42400f21-58b5-4e8c-b19a-d1d7a84998e3` - `TimeoutError()`
`45d2914d-0337-42dd-bc60-e21986a9145f` - `RuntimeError('Lock is not acquired.',)`
`9c7ee332-68e1-4af1-9bbe-1d631e9fc8cf` - `RuntimeError('Lock is not acquired.',)`
`7b6b00de-581d-4102-8749-10839a517403` - `TimeoutError()`

**Comment by mvandeberg** [comment]
This probably has more to do with prod steemd than Jussi. If that is the case, it should be significantly better with appbase. Working on getting a new version of steemd/develop in dev where we can confirm my suspicion.

**Comment by mvandeberg** [comment]
However, get_content should be safe to cache for a significant period of time with the exception of edits. It would be nice to have a smarter cache system that can dirty content on edit.

**Comment by roadscape** [comment]
> If that is the case, it should be significantly better with appbase. 

That's great to hear. My concern is that the instability started with a recent deployment of jussi.

> However, get_content should be safe to cache for a significant period of time with the exception of edits. It would be nice to have a smarter cache system that can dirty content on edit.

I believe `get_content` is currently set to cache for 3s. Hive calls get_content when it detects an edit/vote so it's critical to get the latest state. 3s might actually be too much if we weren't trailing by a couple blocks.

**Comment by sneak** [comment]
Other users are reporting issues as well - see #88
